CREATE PROC FI_SP_ConsBeneficiario
    @IDCLIENTE BIGINT
AS
BEGIN
    SET NOCOUNT ON;

    SELECT
        ID,
        CPF,
        NOME,
        IDCLIENTE
    FROM BENEFICIARIOS WITH (NOLOCK)
    WHERE IDCLIENTE = @IDCLIENTE
END
